const chat=document.getElementById("chat"),form=document.getElementById("messageForm"),input=document.getElementById("messageInput"),sendBtn=document.getElementById("sendBtn"),clearBtn=document.getElementById("clearBtn"),statusEl=document.getElementById("status"),chatList=document.getElementById("chatList"),newChatBtn=document.getElementById("newChatBtn"),signInBtn=document.getElementById("signInBtn"),signOutBtn=document.getElementById("signOutBtn"),accountText=document.getElementById("accountText"),statusDot=document.getElementById("statusDot"),toast=document.getElementById("toast");
const STORAGE_KEY="danial_ai_chats_v2",ACTIVE_KEY="danial_ai_active_chat_v2";let chats=loadChats(),activeChatId=localStorage.getItem(ACTIVE_KEY)||null,busy=false;
marked.setOptions({gfm:true,breaks:true});
function makeId(){return"chat_"+Date.now()+"_"+Math.random().toString(36).slice(2,8)}function loadChats(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");return Array.isArray(v)?v:[]}catch{return[]}}function saveChats(){localStorage.setItem(STORAGE_KEY,JSON.stringify(chats))}function makeTitle(t){t=t.replace(/\s+/g," ").trim();return t.length>42?t.slice(0,42).trim()+"…":t||"New chat"}
function createChat(first=""){const c={id:makeId(),title:makeTitle(first),messages:[]};chats.unshift(c);activeChatId=c.id;localStorage.setItem(ACTIVE_KEY,activeChatId);saveChats();renderChatList();return c}function getActiveChat(){return chats.find(c=>c.id===activeChatId)||null}function ensureChat(){return getActiveChat()||createChat()}
function renderChatList(){chatList.innerHTML="";if(!chats.length){const e=document.createElement("div");e.className="section-title";e.textContent="No chats yet";chatList.appendChild(e);return}chats.forEach(c=>{const b=document.createElement("button");b.className="chat-item"+(c.id===activeChatId?" active":"");b.title=c.title;b.textContent=c.title;b.onclick=()=>{activeChatId=c.id;localStorage.setItem(ACTIVE_KEY,activeChatId);renderChatList();renderActiveChat()};chatList.appendChild(b)})}
function renderActiveChat(){const c=getActiveChat();chat.innerHTML="";if(!c||!c.messages.length){chat.innerHTML='<div class="welcome"><div class="welcome-icon">✦</div><h2>How can I help?</h2><p>Ask anything. Your messages are answered by GPT-5.6 Luna through Puter.</p></div>';return}c.messages.forEach(m=>addMessage(m.role,m.content,false));chat.scrollTop=chat.scrollHeight}
function addMessage(role,text="",save=true){const w=document.createElement("div");w.className=`message ${role}`;const b=document.createElement("div");b.className="bubble";role==="assistant"?renderMarkdown(b,text):b.textContent=text;w.appendChild(b);chat.appendChild(w);if(save){const c=ensureChat();c.messages.push({role,content:text});saveChats()}chat.scrollTop=chat.scrollHeight;return b}
function renderMarkdown(b,text){b.innerHTML=marked.parse(text||"");b.querySelectorAll("pre code").forEach(code=>{try{hljs.highlightElement(code)}catch{}const x=document.createElement("button");x.className="code-copy";x.textContent="Copy";x.onclick=async()=>{try{await navigator.clipboard.writeText(code.textContent);x.textContent="Copied!";setTimeout(()=>x.textContent="Copy",1200)}catch{x.textContent="Failed";setTimeout(()=>x.textContent="Copy",1200)}};code.parentElement.appendChild(x)})}
function updateAssistantBox(b,text){renderMarkdown(b,text);chat.scrollTop=chat.scrollHeight}function setBusy(v){busy=v;sendBtn.disabled=v;input.disabled=v;statusEl.textContent=v?"Danial AI is thinking…":""}function showToast(t){toast.textContent=t;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),2400)}
function refreshAuthUI(){const ok=typeof puter!=="undefined"&&puter.auth.isSignedIn();statusDot.classList.toggle("online",ok);signInBtn.classList.toggle("hidden",ok);signOutBtn.classList.toggle("hidden",!ok);accountText.textContent=ok?"Signed in":"Sign in";return ok}
async function signIn(){try{await puter.auth.signIn();refreshAuthUI();showToast("Signed in to Puter.")}catch(e){showToast(e?.message||e?.msg||e?.error||"Sign in was cancelled.")}}function signOut(){try{puter.auth.signOut();refreshAuthUI();showToast("Signed out.")}catch(e){showToast(e?.message||"Could not sign out.")}}
async function askDanialAI(question,box){if(!puter.auth.isSignedIn())throw new Error("Please sign in with Puter before sending a message.");const c=ensureChat();const req=[{role:"system",content:"You are Danial AI, a helpful, friendly AI assistant. Answer clearly and accurately. Reply in the same language as the user when appropriate. When writing code, use Markdown fenced code blocks with the correct language tag."},...c.messages];const res=await puter.ai.chat(req,{model:"gpt-5.6-luna",stream:true,normalize:true});let answer="";for await(const part of res){if(part.type==="error")throw new Error(part.message||part.msg||part.error||"Puter AI returned an error.");if(part.text){answer+=part.text;updateAssistantBox(box,answer)}}if(!answer.trim())throw new Error("Puter returned an empty response.");c.messages.push({role:"assistant",content:answer});saveChats()}
form.onsubmit=async e=>{e.preventDefault();const q=input.value.trim();if(!q||busy)return;if(!refreshAuthUI()){addMessage("assistant","Please **sign in with Puter** first. You can use the **Sign in** button at the bottom-left.",true);return}let c=getActiveChat();if(!c)c=createChat(q);else if(!c.messages.length){c.title=makeTitle(q);saveChats();renderChatList()}input.value="";input.style.height="auto";addMessage("user",q,true);const box=addMessage("assistant","",false);setBusy(true);try{await askDanialAI(q,box)}catch(e){renderMarkdown(box,`**Error:** ${e?.message||e?.msg||e?.error||"Unknown error."}`)}finally{setBusy(false);input.focus()}};
input.oninput=()=>{input.style.height="auto";input.style.height=Math.min(input.scrollHeight,150)+"px"};input.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();form.requestSubmit()}};newChatBtn.onclick=()=>{createChat();renderActiveChat();input.focus()};clearBtn.onclick=()=>{const c=getActiveChat();if(!c)return;c.messages=[];c.title="New chat";saveChats();renderChatList();renderActiveChat();input.focus()};signInBtn.onclick=signIn;signOutBtn.onclick=signOut;
renderChatList();if(activeChatId&&!getActiveChat())activeChatId=null;renderActiveChat();setTimeout(()=>{try{refreshAuthUI()}catch{}},300);
